controller_manager:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  ros__parameters:
    controller_names:
      - xarm6_traj_controller

    xarm6_traj_controller:
      type: FollowJointTrajectory
      action_ns: follow_joint_trajectory
      default: true
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6