controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xarm6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

xarm6_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0